export const product = [
  {
    id: "1",
    product_name: "Chlorine Granular",
    country: "RRC",
    type: "Granul",
    package: "Kg/Pail",
    img: "img/product-1.jpg",
  },
  {
    id: "2",
    product_name: "Chlorine Tablet",
    country: "RRC",
    type: "Kg/Pail",
    package: "Tablet",
    img: "img/product-2.jpg",
  },
  {
    id: "3",
    product_name: "Liquid HCL",
    country: "Chiwi Chemical",
    type: "Liquid",
    package: "Jerry Can",
    img: "img/product-3.jpg",
  },
  {
    id: "4",
    product_name: "Tawas",
    country: "Japan",
    type: "Crystal",
    package: "Kg",
    img: "img/product-4.jpg",
  },
  {
    id: "5",
    product_name: "Sodium Hypo",
    country: "Chiwi Chemical",
    type: "Liquid",
    package: "Jerry Can",
    img: "img/product-5.jpg",
  },
  {
    id: "6",
    product_name: "PAC Powder",
    country: "Germany",
    type: "Powder",
    package: "5ltr",
    img: "img/product-6.jpg",
  },
  {
    id: "7",
    product_name: "Terusi",
    country: "Japan",
    type: "Crystal",
    package: "Zack/Kg",
    img: "img/product-7.jpg",
  },
  {
    id: "8",
    product_name: "Caustic Soda",
    country: "RRC",
    type: "Crystal",
    package: "Zack/Kg",
    img: "img/product-8.jpg",
  },
  {
    id: "9",
    product_name: "Soda Ash",
    country: "Japan",
    type: "Powder",
    package: "Kg",
    img: "img/product-9.jpg",
  },
  {
    id: "10",
    product_name: "Tawas",
    country: "Japan",
    type: "Powder",
    package: "Kg",
    img: "img/product-10.jpg",
  },
  {
    id: "11",
    product_name: "Salt Industrial",
    country: "Indonesia",
    type: "Crystal",
    package: "Zack",
    img: "img/product-11.jpg",
  },
  {
    id: "12",
    product_name: "Silica Sand",
    country: "Indonesia",
    type: "Granul",
    package: "Zack",
    img: "img/product-12.jpg",
  },
  {
    id: "13",
    product_name: "Kaporit",
    country: "-",
    type: "Powder",
    package: "Zack/Pail",
    img: "img/product-13.jpg",
  },
  {
    id: "14",
    product_name: "Ball Valve Astral",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-14.jpg",
  },
  {
    id: "15",
    product_name: "Check Valve Astral",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-15.jpg",
  },
  {
    id: "16",
    product_name: "Inlet & Vacuum Fitting",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-16.jpg",
  },
  {
    id: "17",
    product_name: "Pool Brush",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-17.jpg",
  },
  {
    id: "18",
    product_name: "Algae Brush",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-18.jpg",
  },
  {
    id: "19",
    product_name: "Leaf Skimmer",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-19.jpg",
  },
  {
    id: "20",
    product_name: "Vaccum Head 8 Wheels",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-20.jpg",
  },
  {
    id: "21",
    product_name: "Vaccum Hose 9 meter",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-21.jpg",
  },
  {
    id: "22",
    product_name: "Telescopic Handle 16",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-22.jpg",
  },
  {
    id: "23",
    product_name: "Test Kit Liquid",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-23.jpg",
  },
  {
    id: "24",
    product_name: "Test Kit Set",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-24.jpg",
  },
  {
    id: "25",
    product_name: "Stick Vacuum",
    country: "-",
    type: "Accessories",
    package: "Pcs",
    img: "img/product-25.jpg",
  },
];
